### ISSUE TITLE
Package in Debugger Has Issues With Values

### ISSUE THREAD

**Issue by JasonBock** [JasonBock/SpackleNet#26]
If I debug this code where it's reference Spackle as a package:
```
var range = 1..50000;
var partitions = range.Partition(7);
Console.Out.WriteLine(partitions.Length);

foreach(var partition in partitions)
{
	Console.Out.WriteLine($"{partition}\t\t{partition.End.Value - partition.Start.Value}");
}
```
When I step into `Partition()`, I get the code in the debugger as expected, but...the local values seem "off": 
![image](https://user-images.githubusercontent.com/904213/81482396-4f831c00-91fc-11ea-8545-e45acaa749b6.png)

**Comment by richlander** [comment]
I see the same thing, although my experience is slightly worse. I don't get an instruction pointer (the yellow arrow) and it is getting confused on whether RangeExtensions.cs is loaded or not. 

I'll ask for some help.

![image](https://user-images.githubusercontent.com/2608468/82152400-bf556000-9815-11ea-88cb-e3da812da095.png)

**Comment by richlander** [comment]
Not likely it, but when you build this library, is your working tree clean? If you type `git status` before you build, you should see: `nothing to commit, working tree clean`.

**Comment by JasonBock** [comment]
@richlander I looked, and right now `git status` is giving what you expected it would. But, I don't remember if I built the .nupkg and .snupkg with everything committed as expected. I'll try making a new version and *ensure* the status of the repo is good.

**Comment by JasonBock** [comment]
@richlander I pushed a 9.1.5 version, making sure the repo was in the expected status when I built it, and I'm still seeing the issue :(

**Comment by tommcdon** [comment]
@JasonBock please try enabling "Suppress JIT optimizations on module load (Managed only)" under Debug->Options

![image](https://user-images.githubusercontent.com/12520929/82250202-df614e00-98ff-11ea-9790-914cf67b6fe6.png)

**Comment by JasonBock** [comment]
That seems to have done the trick :)

One thing....I would've never figured this out myself. It may be worth updating any related docs on this topic to enable this setting (or it may already exist and I missed it).
